# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import inbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privateconversation',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterField(
            model_name='privateconversation',
            name='id',
            field=models.IntegerField(default=inbox.models.random_unique_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
