# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20160713_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('hidden', 'Hidden')], default='open', max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('title', 'status')]),
        ),
        migrations.AddField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to='forum.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('title', 'section')]),
        ),
    ]
