# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20160918_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateconversation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='privateconversation',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='PrivateConversation',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
